---
- name: Install SQL Database
  block:
    - name: Install MySQL
      ansible.builtin.package:
        name: "{{ mysql_pkg }}"
      register: mysql_install
      when: zoneminder_db | lower  == "mysql"

    - name: Install MariaDB
      ansible.builtin.package:
        name: mariadb-server
      register: mariadb_install
      when: zoneminder_db | lower  == "mariadb"

    - name: Configure MariaDB
      ansible.builtin.copy:
        src: 50-server.cnf
        dest: /etc/mysql/mariadb.conf.d/50-server.cnf
        mode: "0644"
      when: zoneminder_db | lower  == "mariadb"

- name: Restart MySQL
  ansible.builtin.service:
    name: mysql
    state: restarted
  when: mysql_install.changed or mariadb_install.changed

- name: Secure MySQL
  ansible.builtin.include_tasks: db-secure.yml
  when: zoneminder_secure_db
