- name: Secure MySQL | Install MySQL Python Connector
  ansible.builtin.package:
    name: "{{ mysql_pkg_py_connector }}"

- name: Secure MySQL | Remove Anonymous Users
  become: true
  community.mysql.mysql_user:
    name: ""
    host_all: true
    state: absent
    login_unix_socket: /run/mysqld/mysqld.sock

- name: Secure MySQL | Remove Test Database
  become: true
  community.mysql.mysql_db:
    name: test
    state: absent
    login_unix_socket: /run/mysqld/mysqld.sock
