---
- name: Install Dependencies
  ansible.builtin.package:
    name:
      - "{{ apache_pkg }}"
      - software-properties-common

- name: Add ZM Repository
  block:
    - name: Create Keyrings Folder
      ansible.builtin.file:
        path: /etc/apt/keyrings
        state: directory
        owner: root
        group: root
        mode: "0755"

    - name: Add ZM Repository Key
      ansible.builtin.get_url:
        url: "{{ zm_repo_key }}"
        dest: /etc/apt/keyrings/zoneminder.asc
        mode: "0644"
        checksum: "sha256:{{ zm_repo_key_checksum }}"

    - name: Add ZM Repository
      ansible.builtin.apt_repository:
        repo: "deb [signed-by=/etc/apt/keyrings/zoneminder.asc] {{ zm_repo }}"
        filename: zoneminder
        state: present

- name: Install and Configure ZM
  notify:
    - "Start ZM Service"
    - "Configure Apache"
  block:
    - name: Install ZM Package
      ansible.builtin.apt:
        update_cache: yes
        pkg: zoneminder
      register: zm_install

    - name: Configure ZM
      ansible.builtin.template:
        src: zm.conf.j2
        dest: /etc/zm/zm.conf
        owner: root
        group: www-data
        mode: "0644"

    - name: Create ZM Database and User
      ansible.builtin.include_tasks: db-zm.yml

    - name: Update ZM Service File
      ansible.builtin.copy:
        src: zoneminder.service
        dest: /lib/systemd/system/zoneminder.service
        owner: root
        group: root
        mode: "0644"

- name: Add User 'www-data' to Group 'video'
  ansible.builtin.user:
    name: www-data
    group: video
