---
- name: Load OS specific variables
  ansible.builtin.include_vars: "{{ ansible_distribution | lower }}.yml"

- name: Install SQL Database
  ansible.builtin.include_tasks: db-install.yml

- name: Install Zoneminder
  ansible.builtin.include_tasks: "{{ ansible_os_family | lower }}.yml"

- name: Install SMTP Packages
  ansible.builtin.include_tasks: smtp.yml
  when: zm_smtp
