---
- name: Converge
  hosts: all
  pre_tasks:
    - name: Set APT cache server # LOCAL DEVELOPMENT - use cache server
      ansible.builtin.copy:
        src: 02proxy
        dest: /etc/apt/apt.conf.d
        owner: root
        group: root
        mode: "0644"
      when: ansible_os_family == 'Debian'

    - name: Update APT cache
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 600
      when: ansible_os_family == 'Debian'
      changed_when: false

    - name: Ensure a locale exists
      block:
        - name: Install Locales
          ansible.builtin.package:
            name: locales

        - name: Add Locale
          community.general.locale_gen:
            name: en_US.UTF-8
            state: present

  roles:
    - name: Install Zoneminder
      role: trfore.zoneminder
      vars:
        zoneminder_db_user: "zm_server"
        zoneminder_db_pass: "mypa$sw0rd"
        zoneminder_db: mariadb
        zoneminder_secure_db: true
        zoneminder_smtp: true
