---
- name: Verify
  hosts: all
  gather_facts: true
  tasks:
    - name: Set Apache Name
      ansible.builtin.set_fact:
        apache: "{{ 'apache2' if ansible_os_family == 'Debian' else 'httpd' }}"

    - name: Test | Check for Files
      ansible.builtin.include_tasks: ../file-check.yml
      loop:
        - /etc/{{ apache }}/conf-enabled/zoneminder.conf
        - /etc/{{ apache }}/mods-enabled/cgi.load
        - /etc/{{ apache }}/mods-enabled/rewrite.load

    - name: Test | Get ZM Config File
      ansible.builtin.stat:
        path: /etc/zm/zm.conf
      register: zm_cfg

    - name: Test | Check ZM Config File
      ansible.builtin.assert:
        that:
          - zm_cfg.stat.pw_name == 'root'
          - zm_cfg.stat.gr_name == 'www-data'

    - name: Test | Check Services
      ansible.builtin.include_tasks: ../service-check.yml
      loop:
        - "{{ apache }}.service"
        - mysql.service
        - zoneminder.service
