---
- name: Verify
  hosts: all
  gather_facts: true
  tasks:
    - name: Get for Zoneminder Apache Config
      ansible.builtin.stat:
        path: /etc/apache2/conf-enabled/zoneminder.conf
      register: apache_config_zm

    - name: Check for Zoneminder Apache Config
      ansible.builtin.assert:
        that: apache_config_zm.stat.exists

    - name: Get for Apache Module - CGI
      ansible.builtin.stat:
        path: /etc/apache2/mods-enabled/cgi.load
      register: apache_module_cgi

    - name: Check for Apache Module - CGI
      ansible.builtin.assert:
        that: apache_module_cgi.stat.exists

    - name: Get for Apache Module - Rewrite
      ansible.builtin.stat:
        path: /etc/apache2/mods-enabled/rewrite.load
      register: apache_module_rewrite

    - name: Check for Apache Module - Rewrite
      ansible.builtin.assert:
        that: apache_module_rewrite.stat.exists

    - name: Get ZM Config File
      ansible.builtin.stat:
        path: /etc/zm/zm.conf
      register: zm_cfg

    - name: Check ZM Config File
      ansible.builtin.assert:
        that:
          - zm_cfg.stat.pw_name == 'root'
          - zm_cfg.stat.gr_name == 'www-data'

    - name: Check for Zoneminder
      ansible.builtin.uri:
        url: http://127.0.0.1/zm
        status_code: 200
        validate_certs: false
      register: result
      until: result.status == 200
      retries: 12
      delay: 10
