name: Update Zoneminder Version
on:
  workflow_dispatch:
  schedule:
    - cron: "15 5 15 * *"
jobs:
  update_dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Check out codebase
        uses: actions/checkout@v4

      - name: Get latest Zoneminder release
        id: release
        run: |
          URL="https://api.github.com/repos/ZoneMinder/zoneminder/releases/latest"
          latest_version=$(curl -X GET  $URL | jq -rS '.tag_name')
          echo "latest_version=$latest_version" >> $GITHUB_OUTPUT

          # get last version tested
          repo_version=$(<zoneminder.version)
          echo "repo_version=$repo_version" >> $GITHUB_OUTPUT

      - name: Update 'zoneminder.version' file
        if: steps.release.outputs.repo_version != steps.release.outputs.latest_version
        env:
          RELEASE_TAG: ${{ steps.release.outputs.latest_version }}
        run: |
          # update 'zoneminder.version' file
          echo ${{ steps.release.outputs.latest_version }} > zoneminder.version

      - name: Create pull request
        if: steps.release.outputs.repo_version != steps.release.outputs.latest_version
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.WORKFLOW_TOKEN }}
          commit-message: "chore: update version to ${{ steps.release.outputs.latest_version }}"
          title: Update zoneminder.version file to ${{ steps.release.outputs.latest_version }}
          body: |
            Updates the zoneminder.version file to ${{ steps.release.outputs.latest_version }},
            this file is used to test the Ansible role against the latest [Zoneminder][1] release.

            Auto-generated by [create-pull-request][2]

            [1]: https://github.com/ZoneMinder/zoneminder
            [2]: https://github.com/peter-evans/create-pull-request
          labels: dependencies, status/auto-created
          branch: update-zm-version
